### ISSUE TITLE
Range's fields is mutable

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Ranges#58]
https://github.com/linksplatform/Ranges/blob/3c683a72bfa23f80afd6d4d6c92aa641995a8837/cpp/Platform.Ranges/Range%5BT%5D.h#L6-L8
https://github.com/linksplatform/Ranges/blob/3c683a72bfa23f80afd6d4d6c92aa641995a8837/csharp/Platform.Ranges/Range%5BT%5D.cs#L21-L31

We must use `const` to copy `readonly` logic

**Comment by Konard** [comment]
I have created an issue about this in the translator's repository: https://github.com/linksplatform/RegularExpressions.Transformer.CSharpToCpp/issues/56

**Comment by uselessgoddess** [comment]
Fixed #61
