### ISSUE TITLE
Maybe change string view for Ranges

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Ranges#60]
We can use [Rust-style](https://doc.rust-lang.org/std/ops/struct.Range.html) (no python) for string view 
```cpp
Range(1, 10) // ==> [1..10] instead of [1, 10]
```

Also `[x, y]` is pair-like array view

**Comment by Konard** [comment]
Give a more detailed example of what do you suggest?

**Comment by uselessgoddess** [comment]
```c++
std::cout << Range{1, 10}; // [1..10]
```

**Comment by uselessgoddess** [comment]
Instead `[1, 10]`

**Comment by Konard** [comment]
I use `[1, 10]` because this Range have exactly the same meaning as [interval from mathematics](https://en.wikipedia.org/wiki/Interval_(mathematics)).

**Comment by uselessgoddess** [comment]
Also mathematics style 
![image](https://user-images.githubusercontent.com/68294279/126621363-8508f713-570c-497d-af0e-43c7bc474de3.png)

**Comment by Konard** [comment]
Well, I didn't see `[a .. b]` notation when I was learning school. We have to make research that will show which of these options is more common.

**Comment by uselessgoddess** [comment]
So many people think that my style is better
![image](https://user-images.githubusercontent.com/68294279/126622359-d842a638-beb7-476e-a449-5c4bc6450a4b.png)

**Comment by Konard** [comment]
> So many people think that my style is better
> ![image](https://user-images.githubusercontent.com/68294279/126622359-d842a638-beb7-476e-a449-5c4bc6450a4b.png)

That is not enough.
