### ISSUE TITLE
Add specialization for std::equal_to here to have solid example of equivalent of Equals method from C#

### ISSUE THREAD

**Issue by Konard** [linksplatform/Ranges#74]
A place where `equal_to` specialization should be placed:

https://github.com/linksplatform/Ranges/blob/8b5062f6b1f90695afeaca650d86ab4b58ebf25a/cpp/Platform.Ranges/Range%5BT%5D.h#L77-L89

Example of `std::equal_to` specialization:

https://github.com/linksplatform/Equality/blob/0ba62efa22e385ed7cd3448ffb74a2a62ced0ddb/cpp/Platform.Equality/Platform.Equality.Range.h#L7-L18

**Comment by uselessgoddess** [comment]
Specialization is not needed. `std::equal_to` require `operator==()`
